/*

MIT License

Copyright (c) 2026 Nicolas "Pixel" Noble

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

// OVERDRAW
//
// The ordering table is the board. Every tile is one entry in it, and the only
// verb in the game is sliding a tile one slot forward or backward. There is no
// collision layer, no height map, no second copy of the world - the walker
// asks the same question the GPU answers, which tile owns the topmost visible
// pixel of this column, and the answer decides whether it walks, burns, or
// flies.
//
// The GPU has no depth buffer. Nothing here pretends otherwise.

#include "psyqo/application.hh"
#include "psyqo/font.hh"
#include "psyqo/fragments.hh"
#include "psyqo/gpu.hh"
#include "psyqo/ordering-table.hh"
#include "psyqo/primitives/rectangles.hh"
#include "psyqo/scene.hh"
#include "psyqo/simplepad.hh"

#include "levels.hh"
#include "walk.hh"

// Generated by the host solver: one winning order per level, and par, the
// fewest slides from the shipped order to any winning order. Par is displayed;
// the solutions themselves are only used by the AUTOPLAY attract build, which
// exists because this box cannot inject controller input into a headless
// emulator and the run path would otherwise never be seen, only asserted.
#include "solutions.inc"

using namespace overdraw;

namespace {

constexpr unsigned kMaxTiles = 12;
// One bucket per tile plus bucket 0 for the overlay, which must land in front
// of everything. Rounded up because the cost is four bytes a bucket.
constexpr unsigned kOrderingTableSize = 32;

constexpr psyqo::Color kBackground = {{.r = 14, .g = 14, .b = 24}};
constexpr psyqo::Color kWhite = {{.r = 255, .g = 255, .b = 255}};
constexpr psyqo::Color kDim = {{.r = 120, .g = 120, .b = 140}};
constexpr psyqo::Color kWalkerColor = {{.r = 250, .g = 250, .b = 255}};

psyqo::Color colorFor(Surface surface) {
    switch (surface) {
        case Surface::Solid: return {{.r = 104, .g = 108, .b = 124}};
        case Surface::Hazard: return {{.r = 206, .g = 48, .b = 32}};
        case Surface::Spring: return {{.r = 232, .g = 190, .b = 48}};
        case Surface::Tar: return {{.r = 74, .g = 42, .b = 96}};
        case Surface::Goal: return {{.r = 56, .g = 196, .b = 104}};
    }
    return kWhite;
}

const char* shortNameFor(Surface surface) {
    switch (surface) {
        case Surface::Solid: return "PLANK";
        case Surface::Hazard: return "LAVA";
        case Surface::Spring: return "SPRING";
        case Surface::Tar: return "TAR";
        case Surface::Goal: return "GOAL";
    }
    return "?";
}

class Overdraw final : public psyqo::Application {
    void prepare() override;
    void createScene() override;

  public:
    psyqo::Font<> m_font;
    psyqo::SimplePad m_pad;
};

class BoardScene final : public psyqo::Scene {
    void start(StartReason reason) override;
    void teardown(TearDownReason reason) override;
    void frame() override;

    void loadLevel(unsigned index);
    void slide(int direction);
    void beginRun();
    void drawRect(psyqo::OrderingTable<kOrderingTableSize>& ot, unsigned parity, unsigned slot,
                  int16_t x, int16_t y, int16_t w, int16_t h, psyqo::Color color, uint32_t z);

  public:
    unsigned m_levelIndex = 0;
    uint8_t m_order[kMaxTiles];
    uint8_t m_selected = 0;
    unsigned m_moves = 0;

    enum class Mode { Edit, Running, Result } m_mode = Mode::Edit;
    Walker m_walker = {0, 0, WalkState::Running};
    unsigned m_resultTimer = 0;

    psyqo::OrderingTable<kOrderingTableSize> m_ots[2];
    psyqo::Fragments::SimpleFragment<psyqo::Prim::FastFill> m_clear[2];
    // Board tiles, order strip swatches, the selection marker's four edges and
    // the walker. Two of each, one per framebuffer parity, because the DMA
    // chain for the previous frame may still be in flight.
    psyqo::Fragments::SimpleFragment<psyqo::Prim::Rectangle> m_tiles[2][kMaxTiles];
    psyqo::Fragments::SimpleFragment<psyqo::Prim::Rectangle> m_swatches[2][kMaxTiles];
    psyqo::Fragments::SimpleFragment<psyqo::Prim::Rectangle> m_marker[2][4];
    psyqo::Fragments::SimpleFragment<psyqo::Prim::Rectangle> m_walkerPrim[2];
    unsigned m_swatchCursor = 0;
    unsigned m_markerCursor = 0;
};

Overdraw g_overdraw;
BoardScene g_boardScene;

}  // namespace

void Overdraw::prepare() {
    psyqo::GPU::Configuration config;
    config.set(psyqo::GPU::Resolution::W320)
        .set(psyqo::GPU::VideoMode::AUTO)
        .set(psyqo::GPU::ColorMode::C15BITS)
        .set(psyqo::GPU::Interlace::PROGRESSIVE);
    gpu().initialize(config);
}

void Overdraw::createScene() {
    m_font.uploadSystemFont(gpu());
    m_pad.initialize();
    pushScene(&g_boardScene);
}

void BoardScene::loadLevel(unsigned index) {
    m_levelIndex = index % g_levelCount;
    const Level& level = g_levels[m_levelIndex];
    for (uint8_t i = 0; i < level.count; i++) m_order[i] = level.order[i];
    m_selected = 0;
    m_moves = 0;
    m_mode = Mode::Edit;
    m_resultTimer = 0;
#ifdef OVERDRAW_AUTOPLAY
    for (uint8_t i = 0; i < level.count; i++) m_order[i] = g_solutions[m_levelIndex][i];
    m_walker = walkStart(level.tiles, m_order, level.count, level.startX);
    m_mode = Mode::Running;
#endif
}

// The player's one verb. Negative moves the selected tile toward the front of
// the ordering table, positive toward the back. Selection follows the tile,
// not the slot, because the player is thinking about the plank and not about
// index four.
void BoardScene::slide(int direction) {
    if (m_mode != Mode::Edit) return;
    const Level& level = g_levels[m_levelIndex];
    int target = static_cast<int>(m_selected) + direction;
    if (target < 0 || target >= level.count) return;
    uint8_t swap = m_order[m_selected];
    m_order[m_selected] = m_order[target];
    m_order[target] = swap;
    m_selected = static_cast<uint8_t>(target);
    m_moves++;
}

void BoardScene::beginRun() {
    if (m_mode != Mode::Edit) return;
    const Level& level = g_levels[m_levelIndex];
    m_walker = walkStart(level.tiles, m_order, level.count, level.startX);
    m_mode = Mode::Running;
}

void BoardScene::start(StartReason reason) {
    loadLevel(0);
    g_overdraw.m_pad.setOnEvent([this](const psyqo::SimplePad::Event& event) {
        if (event.pad != psyqo::SimplePad::Pad::Pad1) return;
        if (event.type != psyqo::SimplePad::Event::ButtonPressed) return;
        const Level& level = g_levels[m_levelIndex];
        switch (event.button) {
            case psyqo::SimplePad::Button::Up:
                if (m_mode == Mode::Edit && m_selected > 0) m_selected--;
                break;
            case psyqo::SimplePad::Button::Down:
                if (m_mode == Mode::Edit && m_selected + 1 < level.count) m_selected++;
                break;
            case psyqo::SimplePad::Button::Left:
                slide(-1);
                break;
            case psyqo::SimplePad::Button::Right:
                slide(1);
                break;
            case psyqo::SimplePad::Button::Cross:
                if (m_mode == Mode::Edit) beginRun();
                break;
            case psyqo::SimplePad::Button::Circle:
                if (m_mode == Mode::Result) loadLevel(m_levelIndex);
                break;
            case psyqo::SimplePad::Button::Start:
                loadLevel(m_levelIndex);
                break;
            case psyqo::SimplePad::Button::Triangle:
                loadLevel(m_levelIndex + 1);
                break;
            default:
                break;
        }
    });
}

void BoardScene::teardown(TearDownReason reason) { g_overdraw.m_pad.setOnEvent(nullptr); }

void BoardScene::drawRect(psyqo::OrderingTable<kOrderingTableSize>& ot, unsigned parity,
                          unsigned slot, int16_t x, int16_t y, int16_t w, int16_t h,
                          psyqo::Color color, uint32_t z) {
    auto& fragment = m_tiles[parity][slot];
    fragment.primitive.position = {{.x = x, .y = y}};
    fragment.primitive.size = {{.x = w, .y = h}};
    fragment.primitive.setColor(color);
    fragment.primitive.setOpaque();
    ot.insert(fragment, z);
}

void BoardScene::frame() {
    const Level& level = g_levels[m_levelIndex];
    const unsigned parity = gpu().getParity();
    auto& ot = m_ots[parity];
    auto& clear = m_clear[parity];

    if (m_mode == Mode::Running) {
        // Two columns per frame: fast enough not to bore, slow enough that you
        // can see exactly which tile killed you.
        for (int i = 0; i < 2; i++) {
            walkStep(level.tiles, m_order, level.count, m_walker);
            if (m_walker.state != WalkState::Running) break;
        }
        if (m_walker.state != WalkState::Running) {
            m_mode = Mode::Result;
            m_resultTimer = 0;
        }
    } else if (m_mode == Mode::Result) {
        m_resultTimer++;
        if (m_walker.state == WalkState::Won && m_resultTimer > 90) {
            loadLevel(m_levelIndex + 1);
        }
    }

    gpu().getNextClear(clear.primitive, kBackground);
    gpu().chain(clear);

    // The board, straight out of the ordering table. Slot 0 is the front of
    // the player's list, so it gets the lowest z and is therefore drawn last.
    // This loop is the entire renderer.
    for (uint8_t slot = 0; slot < level.count; slot++) {
        const Tile& tile = level.tiles[m_order[slot]];
        drawRect(ot, parity, slot, tile.x, tile.y, tile.w, tile.h, colorFor(tile.surface),
                 slot + 1);
    }

    // Overlay lives in bucket 0 and therefore wins against every tile, which is
    // the same rule the board runs on rather than a special case.
    m_swatchCursor = 0;
    for (uint8_t slot = 0; slot < level.count; slot++) {
        const Tile& tile = level.tiles[m_order[slot]];
        auto& fragment = m_swatches[parity][m_swatchCursor++];
        fragment.primitive.position = {{.x = int16_t(18 + slot * 22), .y = 74}};
        fragment.primitive.size = {{.x = 16, .y = 14}};
        fragment.primitive.setColor(colorFor(tile.surface));
        fragment.primitive.setOpaque();
        ot.insert(fragment, 0);
    }

    m_markerCursor = 0;
    if (m_mode == Mode::Edit) {
        const int16_t sx = int16_t(16 + m_selected * 22);
        const int16_t sy = 72;
        const int16_t sw = 20, sh = 18;
        const int16_t edges[4][4] = {
            {sx, sy, sw, 2}, {sx, int16_t(sy + sh - 2), sw, 2},
            {sx, sy, 2, sh}, {int16_t(sx + sw - 2), sy, 2, sh},
        };
        for (const auto& edge : edges) {
            auto& fragment = m_marker[parity][m_markerCursor++];
            fragment.primitive.position = {{.x = edge[0], .y = edge[1]}};
            fragment.primitive.size = {{.x = edge[2], .y = edge[3]}};
            fragment.primitive.setColor(kWhite);
            fragment.primitive.setOpaque();
            ot.insert(fragment, 0);
        }
    }

    if (m_mode != Mode::Edit) {
        auto& fragment = m_walkerPrim[parity];
        fragment.primitive.position = {
            {.x = int16_t(m_walker.x - 3), .y = int16_t(m_walker.y - 13)}};
        fragment.primitive.size = {{.x = 7, .y = 13}};
        fragment.primitive.setColor(kWalkerColor);
        fragment.primitive.setOpaque();
        ot.insert(fragment, 0);
    }

    gpu().chain(ot);

    auto& font = g_overdraw.m_font;
    font.chainprintf(gpu(), {{.x = 8, .y = 6}}, kWhite, "OVERDRAW  %u/%u  %s", m_levelIndex + 1,
                     g_levelCount, level.name);
    font.chainprintf(gpu(), {{.x = 8, .y = 24}}, kDim, "%s", level.hint);

    if (m_mode == Mode::Edit) {
        const Tile& picked = level.tiles[m_order[m_selected]];
        font.chainprintf(gpu(), {{.x = 8, .y = 48}}, kDim, "FRONT %-23s BACK",
                         shortNameFor(picked.surface));
        font.chainprintf(gpu(), {{.x = 8, .y = 104}}, kDim, "UP/DN PICK  L/R SLIDE  X RUN");
        font.chainprintf(gpu(), {{.x = 8, .y = 122}}, kDim, "MOVES %u   PAR %u", m_moves,
                         g_par[m_levelIndex]);
    } else {
        font.chainprintf(gpu(), {{.x = 8, .y = 48}}, kDim, "FRONT %-23s BACK", "");
        if (m_mode == Mode::Running) {
            font.chainprintf(gpu(), {{.x = 8, .y = 104}}, kDim, "RUNNING");
        } else {
            const bool won = m_walker.state == WalkState::Won;
            psyqo::Color result = won ? psyqo::Color{{.r = 80, .g = 240, .b = 120}}
                                      : psyqo::Color{{.r = 240, .g = 90, .b = 70}};
            font.chainprintf(gpu(), {{.x = 8, .y = 104}}, result, "%s",
                             walkStateName(m_walker.state));
            if (!won) {
                font.chainprintf(gpu(), {{.x = 8, .y = 122}}, kDim,
                                 "O RETRY   START RESET   MOVES %u", m_moves);
            } else {
                font.chainprintf(gpu(), {{.x = 8, .y = 122}}, kDim, "%u MOVES, PAR %u", m_moves,
                                 g_par[m_levelIndex]);
            }
        }
    }
}

int main() { return g_overdraw.run(); }
