TARGET = overdraw-selftest
TYPE = ps-exe

SRCS = \
selftest.cpp \
overdraw.cpp \
walk.cpp \
levels.cpp \

CXXFLAGS = -std=c++20

PSYQO_ROOT ?= third_party/nugget

include $(PSYQO_ROOT)/psyqo/psyqo.mk
