TARGET = overdraw-selftest
TYPE = ps-exe

SRCS = \
selftest.cpp \
overdraw.cpp \
walk.cpp \
levels.cpp \

CXXFLAGS = -std=c++20

PSYQO_ROOT ?= /home/pixel/sources/pcsx-redux-wt/overdraw-sdk/src/mips

include $(PSYQO_ROOT)/psyqo/psyqo.mk
