/*

MIT License

Copyright (c) 2026 Nicolas "Pixel" Noble

Host-side level verifier. Builds natively, not for the PS1, and links the same
overdraw.cpp / walk.cpp / levels.cpp the console binary does. That sharing is
the whole point: if this tool and the game ever disagreed about whether a level
is solvable, one of them would be running rules the player never sees.

For each level it reports:
  - whether the SHIPPED starting order already wins (it must not, or the level
    is not a puzzle)
  - how many of the n! orders win at all (0 means the level is broken)
  - the minimum number of player moves to reach a winning order, where one move
    is exactly the verb the game gives you: slide one tile one slot forward or
    backward. That is an adjacent transposition, so the distance is a BFS over
    the permutation graph.

*/

#include <algorithm>
#include <cstdio>
#include <deque>
#include <numeric>
#include <string>
#include <unordered_map>
#include <vector>

#include "levels.hh"
#include "walk.hh"

using namespace overdraw;

namespace {

std::string keyOf(const std::vector<uint8_t>& order) {
    return std::string(reinterpret_cast<const char*>(order.data()), order.size());
}

bool wins(const Level& level, const std::vector<uint8_t>& order) {
    return walkAll(level.tiles, order.data(), level.count, level.startX) == WalkState::Won;
}

// Breadth-first over adjacent transpositions from the shipped order. Returns
// the move count of the nearest winning permutation, or -1 if none is
// reachable (which, since adjacent transpositions generate the full symmetric
// group, means none exists at all).
int minimumMoves(const Level& level, const std::vector<uint8_t>& start,
                 std::vector<uint8_t>* solutionOut) {
    std::unordered_map<std::string, int> seen;
    std::deque<std::vector<uint8_t>> queue;
    seen[keyOf(start)] = 0;
    queue.push_back(start);
    while (!queue.empty()) {
        std::vector<uint8_t> current = queue.front();
        queue.pop_front();
        int depth = seen[keyOf(current)];
        if (wins(level, current)) {
            if (solutionOut) *solutionOut = current;
            return depth;
        }
        for (uint8_t i = 0; i + 1 < level.count; i++) {
            std::vector<uint8_t> next = current;
            std::swap(next[i], next[i + 1]);
            std::string key = keyOf(next);
            if (seen.count(key)) continue;
            seen[key] = depth + 1;
            queue.push_back(next);
        }
    }
    return -1;
}

const char* surfaceName(Surface surface) {
    switch (surface) {
        case Surface::Solid: return "solid";
        case Surface::Hazard: return "hazard";
        case Surface::Spring: return "spring";
        case Surface::Tar: return "tar";
        case Surface::Goal: return "goal";
    }
    return "?";
}

}  // namespace

// Writes the solutions this run found into a header the console binary
// compiles in. The console self-test then re-runs the same walker on an R3000
// and has to reach the same verdict. Generating it rather than hand-copying
// means the two targets cannot silently drift apart.
void emitSolutions(const char* path, const std::vector<std::vector<uint8_t>>& solutions,
                   const std::vector<int>& par) {
    std::FILE* out = std::fopen(path, "w");
    if (!out) {
        std::printf("cannot write %s\n", path);
        return;
    }
    std::fprintf(out, "// Generated by solver.cpp. Do not edit.\n");
    std::fprintf(out, "// One winning permutation per level, found by brute force.\n\n");
    for (size_t i = 0; i < solutions.size(); i++) {
        std::fprintf(out, "static const uint8_t s_solution%zu[] = {", i);
        for (size_t j = 0; j < solutions[i].size(); j++) {
            std::fprintf(out, "%s%u", j ? ", " : "", solutions[i][j]);
        }
        std::fprintf(out, "};\n");
    }
    std::fprintf(out, "\nstatic const uint8_t* const g_solutions[] = {");
    for (size_t i = 0; i < solutions.size(); i++) {
        std::fprintf(out, "%ss_solution%zu", i ? ", " : "", i);
    }
    std::fprintf(out, "};\n\n");
    std::fprintf(out, "// Fewest slides from the shipped order to any winning order.\n");
    std::fprintf(out, "static const uint8_t g_par[] = {");
    for (size_t i = 0; i < par.size(); i++) {
        std::fprintf(out, "%s%d", i ? ", " : "", par[i] < 0 ? 0 : par[i]);
    }
    std::fprintf(out, "};\n");
    std::fclose(out);
    std::printf("wrote %s (%zu levels)\n", path, solutions.size());
}

int main(int argc, char** argv) {
    const char* emitPath = nullptr;
    for (int i = 1; i < argc; i++) {
        if (std::string(argv[i]) == "--emit" && i + 1 < argc) emitPath = argv[++i];
    }
    std::vector<std::vector<uint8_t>> solutions;
    std::vector<int> par;
    int failures = 0;
    for (unsigned levelIndex = 0; levelIndex < g_levelCount; levelIndex++) {
        const Level& level = g_levels[levelIndex];
        std::vector<uint8_t> shipped(level.order, level.order + level.count);

        std::vector<uint8_t> permutation(level.count);
        std::iota(permutation.begin(), permutation.end(), 0);
        unsigned winning = 0, total = 0;
        do {
            total++;
            if (wins(level, permutation)) winning++;
        } while (std::next_permutation(permutation.begin(), permutation.end()));

        WalkState shippedResult =
            walkAll(level.tiles, shipped.data(), level.count, level.startX);
        std::vector<uint8_t> solution;
        int moves = minimumMoves(level, shipped, &solution);
        if (solution.empty()) solution = shipped;
        solutions.push_back(solution);
        par.push_back(moves);

        std::printf("=== %u. %-14s  tiles=%u\n", levelIndex + 1, level.name, level.count);
        std::printf("    shipped order  : ");
        for (uint8_t i = 0; i < level.count; i++) std::printf("%u ", shipped[i]);
        std::printf(" -> %s\n", walkStateName(shippedResult));
        std::printf("    winning orders : %u / %u\n", winning, total);
        std::printf("    minimum moves  : %d\n", moves);
        if (moves > 0) {
            std::printf("    one solution   : ");
            for (uint8_t i = 0; i < level.count; i++) std::printf("%u ", solution[i]);
            std::printf("\n");
        }

        if (shippedResult == WalkState::Won) {
            std::printf("    !! BROKEN: ships already solved, there is no puzzle here\n");
            failures++;
        }
        if (winning == 0) {
            std::printf("    !! BROKEN: unsolvable, no ordering wins\n");
            failures++;
            std::printf("    tiles:\n");
            for (uint8_t i = 0; i < level.count; i++) {
                const Tile& tile = level.tiles[i];
                std::printf("      [%u] x=%d..%d y=%d %s\n", i, tile.x, tile.x + tile.w - 1,
                            tile.y, surfaceName(tile.surface));
            }
        }
        std::printf("\n");
    }
    if (failures) {
        std::printf("%d problem(s) found.\n", failures);
        return 1;
    }
    std::printf("all %u levels are solvable and none ship pre-solved.\n", g_levelCount);
    if (emitPath) emitSolutions(emitPath, solutions, par);
    return 0;
}
